-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOWcreZ9LAtWybwOB
X+vzx8an72qP4QuQqW+/JDpN0xygCgYIKoZIzj0DAQehRANCAAQMnRozyq7iuNwj
qYSsXYuljCrrJUKw1OY+VYaY55ropTrXCgq3yuT5yTzPEGB4LVda6Ms9a2X4QKcl
lgpcBzt4
-----END PRIVATE KEY-----