ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "6"

default_platform(:ios)

platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "9ZW6K85GMU",
      issuer_id: "9b81c085-d4e1-4d1b-b23b-e590f745cdf7",
      key_filepath: "certs/api_key.p8",
      duration: 1200,
      in_house: false
    )

    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M"),
      xcodeproj: "LifeAgenda.xcodeproj"
    )

    build_app(
      scheme: "LifeAgenda",
      export_method: "app-store",
      sdk: "iphoneos",
      clean: true,
      output_directory: "./build",
      output_name: "LifeAgenda.ipa",
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='Apple Distribution' DEVELOPMENT_TEAM=J875R59LND PROVISIONING_PROFILE_SPECIFIER='LifeAgenda AppStore'",
      export_options: {
        method: "app-store",
        teamID: "J875R59LND",
        signingStyle: "manual",
        provisioningProfiles: {
          "com.rezaimia.LifeAgenda" => "LifeAgenda AppStore",
          "com.rezaimia.LifeAgendaWidget" => "LifeAgendaWidget AppStore"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end
